
# THIS CURRENT VERSION HAS THE BARE MINIMUM REQUIREMENTS TO RUN THE WHOLE PIPELINE WITH ALL THE MODELS.
# WHILE THIS MAY BE USEFUL FOR DEBUGGING, YOU WILL LIKELY NEED TO ADJUT THIS FILE
# IN ORDER TO GET ACCURATE INSIGHTS ON PERFORMANCE AND ACCURACY

PIPELINE_RUNNER:
  dataset_path: "./dataset/dynamic_dataset.csv"
  model_task: "classification"
  pipelines_names:
    not_baseline: ["ensembled", "tree_based", "support_vector_machine",
                              "naive_bayes", "feed_forward_neural_network", "stacking"]
    baseline: ["baselines"]
  include_plots: True
  serialize_results: True

dataset_runner:
    split_df: 
      p: 0.80
      step: .05
    encoding:
      y_column: "Category"
      train_size: 0.8
      validation_size: 0.1
      test_size: 0.1

preprocessing_runner:
  placeholders: &placeholders
    - null
    - -999
    - "N/A"
    - "missing"
    - ""
    - "-inf"
    - "NaN"
    - "nan"
    - "none"
    - "None"
    - "missing"
  
  default_missing: &default_missing
    placeholders: *placeholders
  default_duplicates: &default_duplicates
    analyze: false
    plot: false
  default_outliers: &default_outliers
    detection_type: percentile
    plot: false
  default_scaling: &default_scaling
    scaler: robust
    plot: false
  default_imbalance: &default_imbalance
    perform: false
    plot: false
  
  baselines:
    missing: *default_missing
    duplicates: *default_duplicates
    outliers: *default_outliers
    scaling: *default_scaling
    imbalance: *default_imbalance

  tree_based:
    missing: *default_missing
    duplicates:
      analyze: true
      plot: true
    outliers: *default_outliers
    scaling:
      scaler: none
      plot: false
    imbalance: *default_imbalance

  support_vector_machine:
    missing: *default_missing
    duplicates:
      analyze: true
      plot: true
    outliers: *default_outliers
    scaling: *default_scaling
    imbalance:
      perform: true
      plot: true

  naive_bayes:
    missing: *default_missing
    duplicates:
      analyze: true
      plot: true
    outliers: *default_outliers
    scaling:
      scaler: standard
      plot: false
    imbalance: *default_imbalance

  feed_forward_neural_network:
    missing: *default_missing
    duplicates:
      analyze: false
      plot: true
    outliers: *default_outliers
    scaling: *default_scaling
    imbalance: *default_imbalance

  ensembled:
    missing: *default_missing
    duplicates:
      analyze: false
      plot: true
    outliers: *default_outliers
    scaling: *default_scaling
    imbalance: *default_imbalance

  stacking:
    missing: *default_missing
    duplicates:
      analyze: true
      plot: true
    outliers: *default_outliers
    scaling: *default_scaling
    imbalance:
      method: none
      plot: false


feature_analysis_runner:
    features_to_encode: ["Reboot"]
    manual_feature_selection:
      mutual_information:
        threshold: 0.2
        delete_features: True
      low_variances:
        threshold: 0.01
        delete_features: True
      vif:
        threshold: 10
        delete_features: True
      pca:
        threshold: 0.95
        delete_features: True
    automatic_feature_selection:
      l1:
        max_iter: 1000
        delete_features: True
      boruta:
        max_iter: 20
        delete_features: True

modelling_runner:
    models_to_exclude:
      ensembled: ["Gradient Boosting", ]
      tree_based: []
      support_vector_machine: ["Linear Support Vector Machine", "Non-linear Support Vector Machine"]
      naive_bayes: []
      feed_forward_neural_network: []
      stacking: ["Stacking"]
      baselines: ["Logistic Regression (baseline)" ]
    hyperparameters:
      grid_space:
        gradient_boosting:
          learning_rate: [0.01, 0.05, 0.1, 0.2]
          subsample: [0.5, 0.75, 1.0]
          n_estimators: [50, 100, 150, 200]
          max_depth: [10, 20, 30]
          min_samples_split: [2, 5, 10]
          min_samples_leaf: [1, 2, 4]
        random_forest:
          n_estimators: [50, 100, 150, 200]
          max_depth: [10, 20, 30]
          min_samples_split: [2, 5, 10]
          min_samples_leaf: [1, 2, 4]
        decision_tree:
          criterion: ['gini', 'entropy']
          max_depth: [10, 20, 30]
          min_samples_split: [2, 5, 10]
          min_samples_leaf: [1, 2, 5]
          max_features: ['sqrt', 'log2']
          ccp_alpha: [0.0, 0.01, 0.1]
      tuner_params:
        max_iter: 20
        epochs: 1
        
    neural_network:
       initial_architecture:
          batch_size: 128
          epochs: 30
          n_layers: 2
          units_per_layer: [512, 512]
          activations: ['relu', 'relu']
          learning_rate: 0.001
    model_assesment:
      comments: "HEAVY TRAINING GOING ON"
      cross_model_metrics: ["f1-score", "recall", "precision", "accuracy"]
      intra_model_metrics: ["f1-score", "recall", "precision", "accuracy"]
      results_summary:
        training_metric: "timeToFit"
        performance_metric: "accuracy"
      results_df_metrics: ["timeToFit", "timeToPredict"]
      per_epoch_metrics: ["accuracy", "loss"]
      best_model_selection_metric: "f1-score"
    serialize_models:
      serialize_best_performing_model: True
      models_to_serialize: []
      pipelines_to_serialize: []
    
    



BOT:
  channel: "#general"