## Preprocessing configuration for each pipeline
# Define common placeholders once and reference by anchor
placeholders: &placeholders
  - null
  - -999
  - "N/A"
  - "missing"
  - ""
  - "-inf"
  - "NaN"
  - "nan"
  - "none"
  - "None"
  - "missing"

# Baseline pipeline uses percentile capping and robust scaling with plots
baselines:
  missing:
    placeholders: *placeholders
    plot: true
  duplicates:
    analyze: false
    remove: false
  outliers:
    detection_type: percentile
    plot: false
  scaling:
    scaler: robust
    plot: true
  imbalance:
    perform: false
    plot: false

# Tree-based pipelines skip imputation plots but drop duplicates and use percentile outlier capping
tree_based:
  missing:
    placeholders: *placeholders
    plot: false
  duplicates:
    analyze: true
    plot: true
  outliers:
    detection_type: percentile
    plot: false
  scaling:
    scaler: none
    plot: false
  imbalance:
    perform: false
    plot: false

# SVM pipeline applies SMOTE for imbalance and plots duplicate analysis
support_vector_machine:
  missing:
    placeholders: *placeholders
    plot: false
  duplicates:
    analyze: true
    plot: true
  outliers:
    detection_type: percentile
    plot: false
  scaling:
    scaler: robust
    plot: false
  imbalance:
    perform: true
    plot: true

# Naive Bayes pipeline similar to tree but without SMOTE
naive_bayes:
  missing:
    placeholders: *placeholders
    plot: false
  duplicates:
    analyze: true
    plot: true
  outliers:
    detection_type: percentile
    plot: false
  scaling:
    scaler: standard
    plot: false
  imbalance:
    perform: false
    plot: false

# Feed-forward NN uses same defaults as ensemble, no duplicate handling
feed_forward_neural_network:
  missing:
    placeholders: *placeholders
    plot: false
  duplicates:
    analyze: false
    plot: true
  outliers:
    detection_type: percentile
    plot: false
  scaling:
    scaler: robust
    plot: false
  imbalance:
    perform: false
    plot: false

# Ensembled pipeline identical to FNN regarding preprocessing
ensembled:
  missing:
    placeholders: *placeholders
    plot: false
  duplicates:
    analyze: false
    plot: true
  outliers:
    detection_type: percentile
    plot: false
  scaling:
    scaler: robust
    plot: false
  imbalance:
    perform: false
    plot: false

# Stacking pipeline drops duplicates and uses default outlier handling
stacking:
  missing:
    placeholders: *placeholders
    plot: false
  duplicates:
    analyze: true
    remove: true
    plot: true
  outliers:
    detection_type: percentile
    plot: false
  scaling:
    scale: true
    scaler: robust
    plot: false
  imbalance:
    method: none
    plot: false
